version: '3.5'

networks:
  test:
    name: jurassic


services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysql-fastapi
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - test
    environment:
      - MYSQL_DATABASE=fastapi
      - MYSQL_USER=admin_db
      - MYSQL_PASSWORD=admin_db
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - test
      
  fastapi:
    image: fast-api-example:latest
    container_name: fastapi
    restart: always
    ports: 
      - 8000:8000
    networks:
      - test
    environment:
      - MYSQL_URL=mysql://admin_db:admin_db@mysql-fastapi:3306/fastapi
    volumes:
      - ./backend:/code/backend
    depends_on:
      mysql_db:
        condition: service_healthy
  
  vue:
    image: vue:latest
    container_name: vue
    restart: always
    ports:
      - 8001:8080
    networks:
      - test
    volumes:
      - ./frontend:/app
